using System;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

/**
* Generated by MongoDB Relational Migrator 
* https://www.mongodb.com/products/relational-migrator 
* Collection: budgets
* Language: C#
* Template: POCO
* Generated on 3/27/24

*/
namespace WhatIfBudget.Mongo.Data.Models {

  /// <summary>
  /// 
  /// </summary>
  public class BudgetsMortgageGoalEntity {
    /// <summary>
    /// Gets or Sets TotalBalance
    /// </summary>
    [BsonElement("totalBalance")]
    public double TotalBalance { get; set; }

    /// <summary>
    /// Gets or Sets InterestRatePercent
    /// </summary>
    [BsonElement("interestRatePercent")]
    public double InterestRatePercent { get; set; }

    /// <summary>
    /// Gets or Sets MonthlyPayment
    /// </summary>
    [BsonElement("monthlyPayment")]
    public double MonthlyPayment { get; set; }

    /// <summary>
    /// Gets or Sets UpdatedOn
    /// </summary>
    [BsonElement("updatedOn")]
    public DateTime UpdatedOn { get; set; }

    /// <summary>
    /// Gets or Sets AdditionalBudgetAllocation
    /// </summary>
    [BsonElement("additionalBudgetAllocation")]
    public double AdditionalBudgetAllocation { get; set; }

    /// <summary>
    /// Gets or Sets EstimatedCurrentValue
    /// </summary>
    [BsonElement("estimatedCurrentValue")]
    public double EstimatedCurrentValue { get; set; }


    /// <summary>
    /// Get the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()  {
      var sb = new StringBuilder();
      sb.Append("class BudgetsMortgageGoalEntity {\n");
      sb.Append("  TotalBalance: ").Append(TotalBalance).Append("\n");
      sb.Append("  InterestRatePercent: ").Append(InterestRatePercent).Append("\n");
      sb.Append("  MonthlyPayment: ").Append(MonthlyPayment).Append("\n");
      sb.Append("  UpdatedOn: ").Append(UpdatedOn).Append("\n");
      sb.Append("  AdditionalBudgetAllocation: ").Append(AdditionalBudgetAllocation).Append("\n");
      sb.Append("  EstimatedCurrentValue: ").Append(EstimatedCurrentValue).Append("\n");
      sb.Append("}\n");
      return sb.ToString();
    }

    /// <summary>
    /// Get the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public string ToJson() {
      return this.ToJson<BudgetsMortgageGoalEntity>();
    }
  }
}
