using System;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

/**
* Generated by MongoDB Relational Migrator 
* https://www.mongodb.com/products/relational-migrator 
* Collection: budgets
* Language: C#
* Template: POCO
* Generated on 3/27/24

*/
namespace WhatIfBudget.Mongo.Data.Models {

  /// <summary>
  /// 
  /// </summary>
  public class BudgetsBudgetIncomesInnerIncomeEntity {
    /// <summary>
    /// Gets or Sets Amount
    /// </summary>
    [BsonElement("amount")]
    public double Amount { get; set; }

    /// <summary>
    /// Gets or Sets Frequency
    /// </summary>
    [BsonElement("frequency")]
    public int Frequency { get; set; }

    /// <summary>
    /// Gets or Sets CreatedOn
    /// </summary>
    [BsonElement("createdOn")]
    public DateTime CreatedOn { get; set; }

    /// <summary>
    /// Gets or Sets UpdatedOn
    /// </summary>
    [BsonElement("updatedOn")]
    public DateTime UpdatedOn { get; set; }

    /// <summary>
    /// Gets or Sets Name
    /// </summary>
    [BsonElement("name")]
    public string Name { get; set; }


    /// <summary>
    /// Get the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()  {
      var sb = new StringBuilder();
      sb.Append("class BudgetsBudgetIncomesInnerIncomeEntity {\n");
      sb.Append("  Amount: ").Append(Amount).Append("\n");
      sb.Append("  Frequency: ").Append(Frequency).Append("\n");
      sb.Append("  CreatedOn: ").Append(CreatedOn).Append("\n");
      sb.Append("  UpdatedOn: ").Append(UpdatedOn).Append("\n");
      sb.Append("  Name: ").Append(Name).Append("\n");
      sb.Append("}\n");
      return sb.ToString();
    }

    /// <summary>
    /// Get the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public string ToJson() {
      return this.ToJson<BudgetsBudgetIncomesInnerIncomeEntity>();
    }
  }
}
