using System;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

/**
* Generated by MongoDB Relational Migrator 
* https://www.mongodb.com/products/relational-migrator 
* Collection: budgets
* Language: C#
* Template: POCO
* Generated on 3/27/24

*/
namespace WhatIfBudget.Mongo.Data.Models {

  /// <summary>
  /// 
  /// </summary>
  public class BudgetsEntity {
    /// <summary>
    /// Gets or Sets Id
    /// </summary>
    [BsonElement("_id")]
    public ObjectId Id { get; set; }

    /// <summary>
    /// Gets or Sets UserId
    /// </summary>
    [BsonElement("userId")]
    public string UserId { get; set; }

    /// <summary>
    /// Gets or Sets Name
    /// </summary>
    [BsonElement("name")]
    public string Name { get; set; }

    /// <summary>
    /// Gets or Sets CreatedOn
    /// </summary>
    [BsonElement("createdOn")]
    public DateTime CreatedOn { get; set; }

    /// <summary>
    /// Gets or Sets UpdatedOn
    /// </summary>
    [BsonElement("updatedOn")]
    public DateTime UpdatedOn { get; set; }

    /// <summary>
    /// Gets or Sets SavingGoal
    /// </summary>
    [BsonElement("savingGoal")]
    public BudgetsSavingGoalEntity SavingGoal { get; set; }

    /// <summary>
    /// Gets or Sets MortgageGoal
    /// </summary>
    [BsonElement("mortgageGoal")]
    public BudgetsMortgageGoalEntity MortgageGoal { get; set; }

    /// <summary>
    /// Gets or Sets InvestmentGoal
    /// </summary>
    [BsonElement("investmentGoal")]
    public BudgetsInvestmentGoalEntity InvestmentGoal { get; set; }

    /// <summary>
    /// Gets or Sets DebtGoal
    /// </summary>
    [BsonElement("debtGoal")]
    public BudgetsDebtGoalEntity DebtGoal { get; set; }

    /// <summary>
    /// Gets or Sets BudgetIncomes
    /// </summary>
    [BsonElement("budgetIncomes")]
    public List<BudgetsBudgetIncomesInnerEntity> BudgetIncomes { get; set; }

    /// <summary>
    /// Gets or Sets BudgetExpenses
    /// </summary>
    [BsonElement("budgetExpenses")]
    public List<BudgetsBudgetExpensesInnerEntity> BudgetExpenses { get; set; }


    /// <summary>
    /// Get the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()  {
      var sb = new StringBuilder();
      sb.Append("class BudgetsEntity {\n");
      sb.Append("  Id: ").Append(Id).Append("\n");
      sb.Append("  UserId: ").Append(UserId).Append("\n");
      sb.Append("  Name: ").Append(Name).Append("\n");
      sb.Append("  CreatedOn: ").Append(CreatedOn).Append("\n");
      sb.Append("  UpdatedOn: ").Append(UpdatedOn).Append("\n");
      sb.Append("  SavingGoal: ").Append(SavingGoal).Append("\n");
      sb.Append("  MortgageGoal: ").Append(MortgageGoal).Append("\n");
      sb.Append("  InvestmentGoal: ").Append(InvestmentGoal).Append("\n");
      sb.Append("  DebtGoal: ").Append(DebtGoal).Append("\n");
      sb.Append("  BudgetIncomes: ").Append(BudgetIncomes).Append("\n");
      sb.Append("  BudgetExpenses: ").Append(BudgetExpenses).Append("\n");
      sb.Append("}\n");
      return sb.ToString();
    }

    /// <summary>
    /// Get the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public string ToJson() {
      return this.ToJson<BudgetsEntity>();
    }
  }
}
