using System;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

/**
* Generated by MongoDB Relational Migrator 
* https://www.mongodb.com/products/relational-migrator 
* Collection: budgets
* Language: C#
* Template: POCO
* Generated on 3/27/24

*/
namespace WhatIfBudget.Mongo.Data.Models {

  /// <summary>
  /// 
  /// </summary>
  public class BudgetsDebtGoalEntity {
    /// <summary>
    /// Gets or Sets UpdatedOn
    /// </summary>
    [BsonElement("updatedOn")]
    public DateTime UpdatedOn { get; set; }

    /// <summary>
    /// Gets or Sets AdditionalBudgetAllocation
    /// </summary>
    [BsonElement("additionalBudgetAllocation")]
    public double AdditionalBudgetAllocation { get; set; }

    /// <summary>
    /// Gets or Sets Debts
    /// </summary>
    [BsonElement("debts")]
    public List<BudgetsDebtGoalDebtsInnerEntity> Debts { get; set; }


    /// <summary>
    /// Get the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()  {
      var sb = new StringBuilder();
      sb.Append("class BudgetsDebtGoalEntity {\n");
      sb.Append("  UpdatedOn: ").Append(UpdatedOn).Append("\n");
      sb.Append("  AdditionalBudgetAllocation: ").Append(AdditionalBudgetAllocation).Append("\n");
      sb.Append("  Debts: ").Append(Debts).Append("\n");
      sb.Append("}\n");
      return sb.ToString();
    }

    /// <summary>
    /// Get the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public string ToJson() {
      return this.ToJson<BudgetsDebtGoalEntity>();
    }
  }
}
